default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ''
  password: ''

development:
  <<: *default
  database: movies_platform_development

test:
  <<: *default
  database: movies_platform_test

production:
  <<: *default
  database: movies_platform_production
  username: movies_platform
  password: <%= ENV['MOVIES_PLATFORM_DATABASE_PASSWORD'] %>
